# Configuración del proyecto SonarQube para Frontend
sonar.host.url=http://localhost:9000

# Identificadores de proyecto
sonar.projectKey=pilas-frontend
sonar.projectName=Pilas! - Frontend
sonar.projectVersion=1.0.0

# Orígenes de código y exclusiones
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, coverage/**

# Idioma y codificación
sonar.sourceEncoding=UTF-8

# Cobertura de pruebas (LCOV)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Indicar dónde residen las pruebas y bajo qué patrón
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js,src/__mocks__/**

# Excluir los archivos de prueba del análisis de código fuente principal
sonar.exclusions=node_modules/**, dist/**, coverage/**, **/*.test.jsx, **/*.test.js, src/__mocks__/**
